FROM python:3.12-slim AS builder

ENV DockerHOME=/home/app/api
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR $DockerHOME
RUN pip install --upgrade pip
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend $DockerHOME
RUN python manage.py collectstatic --noinput